import { zkVerifySession, ZkVerifyEvents, UltrahonkVariant } from "zkverifyjs";
import dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

import fs from "fs";
import path from "path";

// Paths to proof artifacts generated by bb in the magic_square circuit
const TARGET_DIR = path.resolve('../magic_square/target');

const proof        = '0x' + fs.readFileSync(path.join(TARGET_DIR, 'proof')).toString('hex');
const vk           = '0x' + fs.readFileSync(path.join(TARGET_DIR, 'vk')).toString('hex');
const publicInputs = [];  // magic_square has no public inputs — the square is fully private

let statement, aggregationId;

async function main() {
  console.log('Connecting to ZKVerify (Volta Testnet)...');

  const session = await zkVerifySession.start()
    .Volta()
    .withAccount(process.env.SEED_PHRASE);

  session.subscribe([
    {
      event: ZkVerifyEvents.NewAggregationReceipt,
      callback: async (eventData) => {
        console.log("New aggregation receipt:", eventData);
        if (aggregationId == parseInt(eventData.data.aggregationId.replace(/,/g, ''))) {
          let statementPath = await session.getAggregateStatementPath(
            eventData.blockHash,
            parseInt(eventData.data.domainId),
            parseInt(eventData.data.aggregationId.replace(/,/g, '')),
            statement
          );
          console.log("Statement path:", statementPath);
          const statementProof = {
            ...statementPath,
            domainId: parseInt(eventData.data.domainId),
            aggregationId: parseInt(eventData.data.aggregationId.replace(/,/g, '')),
          };
          fs.writeFileSync("aggregation.json", JSON.stringify(statementProof));
        }
      },
      options: { domainId: 0 },
    },
  ]);

  console.log('Submitting Noir UltraHonk proof...');

  const { events, transactionResult } = await session.verify()
    .ultrahonk({ variant: UltrahonkVariant.Plain })
    .execute({
      proofData: {
        vk,
        proof,
        publicSignals: publicInputs,
      },
      domainId: 0,
    });

  events.on(ZkVerifyEvents.IncludedInBlock, (eventData) => {
    console.log("Included in block", eventData);
    statement = eventData.statement;
    aggregationId = eventData.aggregationId;
  });

  const txInfo = await transactionResult;
  console.log("Full tx info:", JSON.stringify(txInfo, null, 2));
}

main();
